#!/usr/bin/env bash
curl -L -o ./vendor/assets/javascripts/bootstrap-transition.js http://twitter.github.com/bootstrap/assets/js/bootstrap-transition.js
curl -L -o ./vendor/assets/javascripts/bootstrap-scrollspy.js http://twitter.github.com/bootstrap/assets/js/bootstrap-scrollspy.js
curl -L -o ./vendor/assets/javascripts/bootstrap-tooltip.js http://twitter.github.com/bootstrap/assets/js/bootstrap-tooltip.js
curl -L -o ./vendor/assets/javascripts/bootstrap-popover.js http://twitter.github.com/bootstrap/assets/js/bootstrap-popover.js
curl -L -o ./vendor/assets/javascripts/bootstrap-dropdown.js http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js
curl -L -o ./vendor/assets/javascripts/bootstrap-modal.js http://twitter.github.com/bootstrap/assets/js/bootstrap-modal.js
curl -L -o ./vendor/assets/javascripts/bootstrap-alert.js http://twitter.github.com/bootstrap/assets/js/bootstrap-alert.js
curl -L -o ./vendor/assets/javascripts/bootstrap-button.js http://twitter.github.com/bootstrap/assets/js/bootstrap-button.js
curl -L -o ./vendor/assets/javascripts/bootstrap-tab.js http://twitter.github.com/bootstrap/assets/js/bootstrap-tab.js
curl -L -o ./vendor/assets/javascripts/bootstrap-collapse.js http://twitter.github.com/bootstrap/assets/js/bootstrap-collapse.js
curl -L -o ./vendor/assets/javascripts/bootstrap-typeahead.js http://twitter.github.com/bootstrap/assets/js/bootstrap-typeahead.js

echo Not Updated: jquery, prettify.js

