#!/usr/bin/env bash
curl -L -o ./app/assets/javascripts/vendor/bootstrap-transitions.js https://raw.github.com/twitter/bootstrap/2.0-wip/js/bootstrap-transitions.js
curl -L -o ./app/assets/javascripts/vendor/bootstrap-alerts.js http://twitter.github.com/bootstrap/1.4.0/bootstrap-alerts.js
curl -L -o ./app/assets/javascripts/vendor/bootstrap-modal.js http://twitter.github.com/bootstrap/1.4.0/bootstrap-modal.js
curl -L -o ./app/assets/javascripts/vendor/bootstrap-popover.js http://twitter.github.com/bootstrap/1.4.0/bootstrap-popover.js
curl -L -o ./app/assets/javascripts/vendor/bootstrap-scrollspy.js http://twitter.github.com/bootstrap/1.4.0/bootstrap-scrollspy.js
curl -L -o ./app/assets/javascripts/vendor/bootstrap-twipsy.js http://twitter.github.com/bootstrap/1.4.0/bootstrap-twipsy.js
curl -L -o ./app/assets/javascripts/vendor/jquery-1.7.min.js http://code.jquery.com/jquery-1.7.min.js

